project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "ASCEND - Data Management"
  navbar:
    right:
    - href: index.qmd
      text: Home
    - text: Data
      menu:
      - href: files/Themes/Theme1.qmd
        text: Theme 1
      - href: files/Themes/Theme2.qmd
        text: Theme 2
      - href: files/Themes/Theme3.qmd
        text: Theme 3
      - href: files/Themes/Theme4.qmd
        text: Theme 4
      - href: files/Themes/Theme5.qmd
        text: Theme 5
    - icon: github
      href: https://github.com/ASCEND-BII
    - icon: global
      href: https://www.spectralbiology.org/

  page-footer: 
    right: "Page updated on 2023-01-22"
    left: "&copy; CC-By ASCEND"
    
format:
  html:
    page-layout: full
    theme:
      light: cosmo
    code-copy: true
    code-overflow: wrap
    toc: false

editor: visual