site_name: BII ASCEND
theme:
  name: material
  logo: 'Images/Logo+circle.png'
  palette:
    - scheme: default
      primary: blue grey
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: lime green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - search.highlight
    - search.share
  font:
    code: Playfair Display
  icon:
    repo: fontawesome/brands/github-alt
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_revision_date: true
  - git-committers:
      repository: ASCEND-BII/Data-management
      token: !ENV GH_TOKEN
  - git-authors
  - table-reader
  - tags
  - encryptcontent:
      remember_password: True
      password_button: True
      password_button_text: 'ENTER'
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
repo_url: https://github.com/ASCEND-BII/Data-management
repo_name: ASCEND-BII/Data-management
edit_uri: ""
nav:
  - Home: 'index.md'
  - Guide: 'Getting-Started.md'
  - Data:
    - Theme 1: 'Theme/Theme1.md'
    - Theme 2: 'Theme/Theme2.md'
    - Theme 3: 'Theme/Theme3.md'
    - Theme 4: 'Theme/Theme4.md'
    - Theme 5: 'Theme/Theme5.md'