site_name: BII ASCEND
theme:
  name: material
  logo: 'Logo+circle.png'
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - search.highlight
    - search.share
  plugins:
    - search
    - offline
nav:
  - Home: 'index.md'
  - Getting Started: 'Getting-Started.md'
  - Institutions:
    - University of Minnesota:
      - Publications: 'UMNpublications.md'
      - Presentations/Conferences/Seminars: ''
    - University of Wisconsin:
      - Data Management: 'sampleUW.md'
      - Publications: 'UWpublications.md'
      - Presentations/Conferences/Seminars: ''
  - About: ''