site_name: BII ASCEND
theme:
  name: material
  logo: 'Logo+circle.png'
  palette:
    - scheme: default
      primary: blue grey
      accent: green
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      primary: blue
      accent: lime green
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - search.highlight
    - search.share
  plugins:
    - search
    - offline
nav:
  - Home: 'index.md'
  - Getting Started: 'Getting-Started.md'
  - Test: ''
  - Institutions:
    - University of Minnesota:
      - Publications: 'UMNpublications.md'
      - Presentations/Conferences/Seminars: ''
    - University of Wisconsin:
      - Data Management: 'sampleUW.md'
      - Publications: 'UWpublications.md'
      - Presentations/Conferences/Seminars: ''
  - About: ''