site_name: BII ASCEND
theme:
  name: material
  logo: 'Logo+circle.png'
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: 'index.md'
  - Institutions:
    - University of Minnesota:
      - Cavender-Bares Lab: 'sampleUMN.md'
      - Reich Lab: 'sampleUMN.md'
    - University of Wisconsin:
      - Townsend: 'sampleUW.md'
  - About: ''