---
title: "Theme 4"
output: github_document
---

## How species interactions within communities and ecosystems influence local carbon and other biogeochemical cycles at ecosystem and landscape scales

| Description                       | Institution             | Location of Data Collection           | Path to Data                                                 | Server               | DOI |
|-----------------------------------|-------------------------|---------------------------------------|--------------------------------------------------------------|----------------------|-----|
| Leaf level spectra of FAB trees   | University of Minnesota | Cedar Creek Ecosystem Science Reserve | Lab-cavender/4_Project_Folders/Cedar_Creek/FAB2/Data/Spectra | UMN CBS shared drive |     |
| Canopy level spectra of FAB trees | University of Minnesita | Cedar Creek Ecosystem Science Reserve | Lab-cavender/4_Project_Folders/Cedar_Creek/FAB2/Data/spectra | UMN CVS shared drive |     |

|                             | Definition                                 |
|-----------------------------|--------------------------------------------|
| Description                 | Brief description including type of data   |
| Institution                 | Primary institution that acquired the data |
| Location of Data Collection | Where was the data collected               |
| Path to Data                | Path to data storage                       |
| Server                      | Server name                                |
| DOI                         | Applicable if used in publication          |
