---
title: ""
---

# Theme 2

### Phenotypic variation across the tree of life - modeling the evolutionary processes that give rise to the genomic, metabolomic and functional trait variation among species

```{r echo=F, results='hide'}
library(DT)
library(data.table)
publications <- fread("themes.csv")
theme2 <- subset(publications, Theme == "2")
theme2 <- theme2[, .SD, .SDcols = c(2:ncol(theme2))]

#Data links ------------------------------------------------------------------------
datalinks <- NA

for(i in 1:nrow(theme2)) {
  
  cell_link <- NA
  
  data <- theme2$Data[i]
  splitdata <- strsplit(data, split = ":&:")
  
  for(ii in 1:length(splitdata[[1]])) {
    
    name <- strsplit(splitdata[[1]][ii], split = "]")
    base <- substr(name[[1]][1], 2, nchar(name[[1]][1]))
    link <- substr(name[[1]][2], 2, (nchar(name[[1]][2])-1))
    urls <-  paste0("<a href='",  link, "'>", base, "</a>")
    
    if(ii == 1) {
      cell_link <- urls
    } else if(ii == length(splitdata[[1]])){
      cell_link <- paste0(cell_link, " and ", urls)
    } else {
      cell_link <- paste0(cell_link, ", ", urls)
    }
  }
  
  datalinks[i] <- cell_link
  
}

theme2$Data <- datalinks

#DOI -------------------------------------------------------------------------------
doilinks <- NA

for(i in 1:nrow(theme2)) {
  
  data <- theme2$Link[i]
  urls <-  paste0("<a href='",  data, "'>", "Link", "</a>")
  
  doilinks[i] <- urls
  
}

theme2$Link <- doilinks
theme2$Citation <- paste0(theme2$Citation, " ", theme2$Link)

#Code links ------------------------------------------------------------------------
codelinks <- NA

for(i in 1:nrow(theme2)) {
  
  cell_link <- NA
  
  data <- theme2$Code[i]
  splitdata <- strsplit(data, split = ":&:")
  
  if(length(splitdata[[1]]) == 0) {
    codelinks[i] <- NA
    
  } else {
    for(ii in 1:length(splitdata[[1]])) {
      
    name <- strsplit(splitdata[[1]][ii], split = "]")
    base <- substr(name[[1]][1], 2, nchar(name[[1]][1]))
    link <- substr(name[[1]][2], 2, (nchar(name[[1]][2])-1))
    urls <-  paste0("<a href='",  link, "'>", base, "</a>")
    
    if(ii == 1) {
      cell_link <- urls
    } else if(ii == length(splitdata[[1]])){
      cell_link <- paste0(cell_link, " and ", urls)
    } else {
      cell_link <- paste0(cell_link, ", ", urls)
    }
    
  }
  codelinks[i] <- cell_link
  }
}

theme2$Code <- codelinks

#--------------------------------------------------------------------
# Selection of columns
theme2 <- theme2[, .SD, .SDcols = c(1:2, 4:6)]
```

<br>

```{r echo=F}
datatable(theme2, rownames= FALSE, escape = FALSE)
```
