---
title: ""
---

# Theme 5

### Advancing Earth System Models to integrate our understanding of how functional trait variation--- as determined spectrally across the tree of life and across ecosystems---influences global biogeochemical cycles and biosphere dynamics

```{r echo=F, results='hide'}
library(DT)
library(data.table)
publications <- fread("themes.csv", encoding = 'UTF-8')
publications <- publications[!is.na(Theme)]
theme <- subset(publications, Theme == "5")
theme <- theme[, .SD, .SDcols = c(2:ncol(theme))]

#Data links -----------------------------------------------------------------------
datalinks <- NA

for(i in 1:nrow(theme)) {
  
  cell_link <- NA
  
  data <- theme$Data[i]
  splitdata <- strsplit(data, split = ":&:")
  
  if(length(splitdata[[1]]) == 0) {
    datalinks[i] <- NA
  } else {
    for(ii in 1:length(splitdata[[1]])) {
    
    name <- strsplit(splitdata[[1]][ii], split = "]")
    base <- substr(name[[1]][1], 2, nchar(name[[1]][1]))
    link <- substr(name[[1]][2], 2, (nchar(name[[1]][2])-1))
    urls <-  paste0("<a href='",  link, "'>", base, "</a>")
    
    if(ii == 1) {
      cell_link <- urls
    } else if(ii == length(splitdata[[1]])){
      cell_link <- paste0(cell_link, " and ", urls)
    } else {
      cell_link <- paste0(cell_link, ", ", urls)
    }
    }
  }
  
  datalinks[i] <- cell_link
  
}

theme$Data <- datalinks

#DOI ------------------------------------------------------------------------------
doilinks <- NA

for(i in 1:nrow(theme)) {
  
  data <- theme$Link[i]
  DOI <- strsplit(data, split = "https://doi.org/")[[1]][2]
  urls <-  paste0("<a href='",  data, "'>", DOI, "</a>")
  doilinks[i] <- paste0("DOI: ", urls, ".")
  
}

theme$Link <- doilinks
theme$Citation <- paste0(theme$Citation, " ", theme$Link)

#Code links -----------------------------------------------------------------------
codelinks <- NA

for(i in 1:nrow(theme)) {
  
  cell_link <- NA
  
  data <- theme$Code[i]
  splitdata <- strsplit(data, split = ":&:")
  
  if(length(splitdata[[1]]) == 0) {
    codelinks[i] <- NA
    
  } else {
    for(ii in 1:length(splitdata[[1]])) {
      
    name <- strsplit(splitdata[[1]][ii], split = "]")
    base <- substr(name[[1]][1], 2, nchar(name[[1]][1]))
    link <- substr(name[[1]][2], 2, (nchar(name[[1]][2])-1))
    urls <-  paste0("<a href='",  link, "'>", base, "</a>")
    
    if(ii == 1) {
      cell_link <- urls
    } else if(ii == length(splitdata[[1]])){
      cell_link <- paste0(cell_link, " and ", urls)
    } else {
      cell_link <- paste0(cell_link, ", ", urls)
    }
    
  }
  codelinks[i] <- cell_link
  }
}

theme$Code <- codelinks

#--------------------------------------------------------------------
# Selection of columns
theme <- theme[, .SD, .SDcols = c(1:2, 4:6)]
```

<br>

```{r echo=F}
datatable(theme, rownames= FALSE, escape = FALSE)
```
